In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(
    "SMSSpamCollection",
    sep="\t",
    header=None,
    names=["label", "message"]
)

In [6]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.shape

(5572, 2)

In [8]:
df.columns

Index(['label', 'message'], dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   str
 1   message  5572 non-null   str
dtypes: str(2)
memory usage: 87.2 KB

In [10]:
df["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [11]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(403)

In [13]:
import sys
print(sys.executable)

c:\Internship_Task\Spam_Mail_Detector\.venv\Scripts\python.exe

In [14]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

print(len(stop_words))
print(list(stop_words)[:10])

198
['into', 'hers', "didn't", 've', 'between', 'does', 'all', "i'd", 'above', 'shouldn']

In [15]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

In [16]:
df["message"].iloc[0].lower()    # First row (by position)

'go until jurong point, crazy.. available only in bugis n great world la e buffet... cine there got amore wat...'

# Tokenization

In [17]:
def preprocess_text(text):
    text = text.lower()
    
    tokens = word_tokenize(text)
    
    tokens = [word for word in tokens if word not in stop_words]
    
    return tokens

In [18]:
df["processed_message"] = df["message"].apply(preprocess_text)

In [19]:
sample = "Congratulations! You have won a free prize."
preprocess_text(sample)

['congratulations', '!', 'free', 'prize', '.']

In [20]:
df["processed_message"] = df["message"].apply(preprocess_text)

In [21]:
df[["message", "processed_message"]].head()

,message,processed_message
0,"Go until jurong point, crazy.. Available only ...","[go, jurong, point, ,, crazy, .., available, b..."
1,Ok lar... Joking wif u oni...,"[ok, lar, ..., joking, wif, u, oni, ...]"
2,Free entry in 2 a wkly comp to win FA Cup fina...,"[free, entry, 2, wkly, comp, win, fa, cup, fin..."
3,U dun say so early hor... U c already then say...,"[u, dun, say, early, hor, ..., u, c, already, ..."
4,"Nah I don't think he goes to usf, he lives aro...","[nah, n't, think, goes, usf, ,, lives, around,..."